### ISSUE TITLE
Versin 1.4 doesn't work with com.android.tools.build:gradle in some situations

### ISSUE THREAD

**Issue by tprochazka** [dcendents/android-maven-gradle-plugin#40]
Previous version was not working with Gradle 2.14 and current version does not working with com.android.tools.build:gradle:2.2.0-alpha5

It crash during project configuration on this exception:

`Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
`

It looks that plugin force to use some old Guava version, but build plugin require newer version. It's weird, because build plugin 2.1.2 use Guava 17 and 2.2.0-alphaX using Guava 18 on some dependencies.

But I not found the Guava as dependency of this plugin, there is just
```
|    |         |    \--- org.sonatype.sisu:sisu-inject-plexus:2.3.0
|    |         |         +--- org.codehaus.plexus:plexus-component-annotations:1.5.5
|    |         |         +--- org.codehaus.plexus:plexus-classworlds:2.4
|    |         |         +--- org.codehaus.plexus:plexus-utils:2.1
|    |         |         \--- org.sonatype.sisu:sisu-inject-bean:2.3.0
|    |         |              \--- org.sonatype.sisu:sisu-guice:3.1.0
|    |         |                   \--- org.sonatype.sisu:sisu-guava:0.9.9
```
Probably it cause the problem.
It contain the same classes but in different groupId and artifactId, so Gradle can't resolve it correctly.
It is really not good idea without change the package path inside :-(

Why your plugin now have so many dependencies and version before has no dependency?

I found that it depends on the order of classpath decency definition.
If right jar is before that old one on the classpath java use it and android build plugin works correctly.
But I didn't test if deploying works correctly.

Question is if is possible to exclude org.sonatype.sisu:sisu-guava:0.9.9 from your plugin.

**Comment by snowdream** [comment]
use 1.4.1,please.

classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'

i have met the simlar error,but now it works.

**Comment by dcendents** [comment]
I'll close this issue, @snowdream confirms it is fixed with 1.4.1
If it is not please reopen it.
